#!groovy
pipeline {
    environment {
        REGISTRY = "afik/argocd-project"
        registryCredential = 'Docker_hub'
        BUILD_NUMBER = "${env.BUILD_ID}"
    }
    agent any
    stages {
         stage('pushing_image') {
             steps {
                 dir('import') {
                    script {
                            echo 'Building Dockerfile'
                              docker.withRegistry( '', registryCredential ) {
                                sh './push_docker_image.sh ${BUILD_NUMBER} ${REGISTRY}'
                              }
                    }
                 }
             }
         }
    }
}


              
