#!groovy
pipeline {
    environment {
        REGISTRY = "afik/argocd-project"
        REGESTRY_CRED = 'Docker_hub'
        BUILD_NUMBER = "${env.BUILD_ID}"
    }
    agent any
    stages {
         stage('pushing_image') {
             steps {
                 dir('import') {
                    script {
                            echo 'Building Dockerfile'
                            withCredentials([usernamePassword(credentialsId: 'Docker_hub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                                sh 'docker login ${USERNAME} -p ${PASSWORD}'
                                sh './push_docker_image.sh ${BUILD_NUMBER} ${REGISTRY}'
                            }
                    }
                 }
             }
         }
    }
}
                    
