apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysqlabel }}
  labels:
    app: {{ .Values.mysqlabel }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysqlabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysqlabel }}
    spec:
      containers:
      - name: {{ .Values.mysqlimagename }}
        image: {{ .Values.imagemysql }}
        env:
          {{- range .Values.sqlenv }}
        - name: {{ .name }}
          value: {{ .value | quote }}
          {{- end }}
        ports:
        - containerPort: 3306
