###values File for deployment###
image: afik/argocd-project:latest
label: spring-petclinic-deployment
labelselector: spring-petclinic-deployment
name: spring-petclinic-deployment
imagename: argocd-project
###values File for service###
servicename: spring-petclinic-service
servicetype: clusterIP
portmapping: 80
servicelabel: spring-petclinic-service
clustertype: ClusterIP
targetportmapping: 8080
###values File for deployment##
imagemysql: mysql:5.7
mysqlabel: spring-petclinic-mysqldb-deployment
mysqlimagename: spring-mysqldb
mysqlselector: spring-petclinic-mysqldb-deployment
sqlenv:
 - name: MYSQL_ROOT_PASSWORD
   value: null
 - name: MYSQL_ALLOW_EMPTY_PASSWORD
   value: true
 - name: MYSQL_USER
   value: petclinic
 - name: MYSQL_USER
   value: petclinic

